# -*- coding: utf-8 -*-
"""nlp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14MhR_9Zkvm1RNYUTarH3pvw0v8YXg7LA

# =====================================
# TEXT CLASSIFICATION PROJECT
# Student Level Project
# Categories: Sports / Food / Technology
# =====================================
"""

#  Libraries
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Create Dataset

data = {
    "Text": [
        "football match goal player stadium",
        "basketball team score coach ball",
        "tennis player win tournament",
        "pizza burger pasta cheese dinner",
        "rice chicken soup tasty meal",
        "coffee cake sweet breakfast",
        "computer keyboard mouse screen laptop",
        "internet coding python software program",
        "mobile phone app technology device"
    ],

    "Category": [
        "Sports",
        "Sports",
        "Sports",
        "Food",
        "Food",
        "Food",
        "Technology",
        "Technology",
        "Technology"
    ]
}

df = pd.DataFrame(data)

X_train, X_test, y_train, y_test = train_test_split(
    df["Text"],
    df["Category"],
    test_size=0.3,
    random_state=42
)

# Convert Text to Numbers

vectorizer = CountVectorizer()

X_train_vector = vectorizer.fit_transform(X_train)
X_test_vector = vectorizer.transform(X_test)

# Train Model

model = MultinomialNB()
model.fit(X_train_vector, y_train)

# Test Model

y_pred = model.predict(X_test_vector)

# Accuracy Score

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

# New Prediction

new_text = ["python coding laptop"]

new_vector = vectorizer.transform(new_text)
result = model.predict(new_vector)

print("\nNew Sentence:", new_text[0])
print("Predicted Category:", result[0])



